### ISSUE TITLE
Scrollbars are overlapped by other window elements.

### ISSUE THREAD

**Issue by Solo-Coder** [JakubSteplowski/devRantUnofficial#12]
As it stands now, scrollbars begin at the top of the windows, right under the title bar, and end at the window's bottom. This results in getting hidden by other UI elements.
Scrollbars should begin with their relevant elements that should be scrolled and end with them.
In the following images, the overlapped part has been coloured in orange and the visible part in yellow.

![example1](https://user-images.githubusercontent.com/5850664/32387426-1d55d176-c0cd-11e7-988e-403b6ffcce49.PNG)
![example2](https://user-images.githubusercontent.com/5850664/32387427-1d8933c2-c0cd-11e7-9c83-f54ba6939fe4.PNG)
![example3](https://user-images.githubusercontent.com/5850664/32387428-1db217b0-c0cd-11e7-9109-a6dc2c8dd576.PNG)

**Comment by JakubSteplowski** [comment]
Sorry, but this is unavoidable if we want to see the Fluent Design effects.
The entire page is under the top and bottom panels, and for this reason also the scrollbars.

This effects wouldn't be possible otherwise:
![screenshot_1](https://user-images.githubusercontent.com/4522930/32387794-e1caf5c0-c0c5-11e7-906f-e661573dac26.png)

I think the position of scrollbars is impossible to be modified, maybe if I had created the scroll viewers from scratch, but it would require too much work.

So it's something I can't fix, sorry.

**Comment by JakubSteplowski** [comment]
Maybe I found a way to fix this and keep the blur effect. Will try in future. :)

**Comment by JakubSteplowski** [comment]
The fix for this issue will be present in the next update, v2.0.0-beta8. :)
