### ISSUE TITLE
Suggestion: A message asking the user to click on rant in Desktop

### ISSUE THREAD

**Issue by Raamakrishnan** [JakubSteplowski/devRantUnofficial#13]
When the app is launched on desktop and when no rant is selected, the right plane looks... blank!
Maybe a small message like "Click on a rant to view comments" and a devrant logo will look good. 
![screenshot 6 _li](https://user-images.githubusercontent.com/9772489/32402083-8108b0d8-c142-11e7-9d57-d3a5c9a7e243.jpg)

**Comment by JakubSteplowski** [comment]
I need to make some concepts to find the best way to show something like this, but it's definitely something which could be cool. Will arrive in future.

**Comment by JakubSteplowski** [comment]
It's very likely that I'll implement a "One Column View" mode when the right panel is closed (maybe enabled by default, but still with the ability to disable it in the settings), and the panels in a future version will be resizable so that part won't be so empty anymore.

Thanks for the suggestion anyway, but I couldn't find a good looking way to implement a message of that kind.
